@startuml
title "Monstre attaquant un Personnage"


participant "monstre : Monstre" as monst
participant "perso : Personnage" as perso

->monst:attaquer(perso)
activate monst
monst->perso:getPV()
activate perso
monst<--perso : pv
deactivate perso
monst->perso:setPV(pv - 1)
activate perso
monst<--perso
deactivate perso
<--monst
deactivate perso

@enduml